// <auto-generated />
using DogApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogApp.Data
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogApp.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<double>("TailLength")
                        .HasColumnType("FLOAT");

                    b.Property<double>("Weight")
                        .HasColumnType("FLOAT");

                    b.HasKey("Id");

                    b.ToTable("Dogs", t =>
                        {
                            t.HasCheckConstraint("CK_TailLength", "TailLength >= 0");

                            t.HasCheckConstraint("CK_Weight", "Weight >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Black",
                            Name = "Jessy",
                            TailLength = 25.0,
                            Weight = 5.0
                        },
                        new
                        {
                            Id = 2,
                            Color = "White",
                            Name = "Neo",
                            TailLength = 15.0,
                            Weight = 3.0
                        },
                        new
                        {
                            Id = 3,
                            Color = "Brown",
                            Name = "Doggy",
                            TailLength = 50.0,
                            Weight = 15.0
                        },
                        new
                        {
                            Id = 4,
                            Color = "White&Brown",
                            Name = "Chessy",
                            TailLength = 10.0,
                            Weight = 2.0
                        },
                        new
                        {
                            Id = 5,
                            Color = "Gray",
                            Name = "Bob",
                            TailLength = 60.0,
                            Weight = 20.0
                        },
                        new
                        {
                            Id = 6,
                            Color = "Black",
                            Name = "Jessy",
                            TailLength = 25.0,
                            Weight = 5.0
                        },
                        new
                        {
                            Id = 7,
                            Color = "Gold",
                            Name = "Marko",
                            TailLength = 70.0,
                            Weight = 30.0
                        },
                        new
                        {
                            Id = 8,
                            Color = "Black",
                            Name = "Fido",
                            TailLength = 100.0,
                            Weight = 25.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
